api-management
redhat-helloworld-msa/frontend pull request #17
Opened 2018-08-09 19:42 UTC by hguerrero

This is the frontend modifications to show the API management tab and test the services using the apicast microgateway.

2018-08-09 22:24 UTC, hguerrero commented
api-management github repo to fork:

https://github.com/hguerrero/api-management.git

2018-08-14 22:51 UTC, rafabene requested changes

2018-08-14 22:51 UTC, rafabene commented on index.html
> +				<img src="images/sso.svg" style="float: right; width: 50%; height: 30em;" />
Is it supposed to have the same image?

2018-08-14 22:51 UTC, rafabene commented on index.html
> -			<li role="presentation"><a href="#apigateway">API Gateway</a></li>
This tab should come between SSO and "Browser as a client". It was inserted in the middle of the "Invocation patterns".

2018-08-14 22:51 UTC, rafabene commented on index.html
> +			<!--  Tab API Management -->
Move here too.

2018-08-14 22:52 UTC, rafabene commented
between SSO and "Browser as a client". It was inserted in the middle of the "Invocation patterns".

2018-08-15 20:24 UTC, hguerrero commented
done, moved between "sso" and "browser as client".

2018-08-16 02:31 UTC, rafabene commented
Merged at https://github.com/redhat-helloworld-msa/frontend/commit/3cb22099f8fafd8007e0f07249e1f99cf054747d

2018-08-16 02:31 UTC, closed without merging